### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by mostarz93** [msabvid/cpm_agent_based_sim#1]
Super interested in doing ABM models for market sims on Ethereum. Curious how/what you are doing to get the chain state. Im assuming you are running a fork locally, but i cant find in the code where you set this up.

Thanks

**Comment by msabvid** [comment]
This code is just a simulation. The price of the risky asset follows a Geometric Brownian Motion (or I also coded a Brownian bridge). There is only one trader in the CPM (the arbitrageur), and the trade sizes are derived from the constant function F(x,y) = x*y, and the CPM reserves are updated accordingly. In summary, everything is synthetic, and there's no need to access chain state.
